### PR TITLE
chore: cleanup solution and fix unresolved symbols in nuget pkg

### PR DESCRIPTION
**Pull request by Ujinjinjin**
@Mezo-hx I've slightly cleaned up the solution, packed it as a nuget package and tested locally - all symbols are resolved as one would expect.

Also:

- retargeted library to `net8.0`
- cleaned up `.gitignore` by removing unnecessary commented sections
- added package icon, since it's referenced in `.csproj` file

### CODE REVIEW

**Comment by Ujinjinjin** [comment]
[MonoGame.ImGuiNet.1.1.0.nupkg.zip](https://github.com/Mezo-hx/MonoGame.ImGuiNet/files/13813004/MonoGame.ImGuiNet.1.1.0.nupkg.zip)

ready to publish nuget pkg

**Comment by Mezo-hx** [comment]
Gotcha!

**Comment by Ujinjinjin** [comment]
@Mezo-hx when can we expect a new package version being published?

**Comment by Mezo-hx** [comment]
> @Mezo-hx when can we expect a new package version being published?

Probably not anytime soon, exactly. I have decided to drop the NuGet package, but if there are a few people who would like it back, then I can try to find time to update it. I can't really be certain now as I've been pretty busy these days, which is also the reason why the library hasn't been updating.

**Comment by Ujinjinjin** [comment]
Ah, gotcha. To save you some time, I can prepare a PR with github actions configured to pack and deploy nuget to the feed automatically

**Comment by Ujinjinjin** [comment]
Also, if you'd share what you'd like to include in potential future updates - would be great. Possibly someone from the community would be able to work on it

**Comment by Mezo-hx** [comment]
> Ah, gotcha. To save you some time, I can prepare a PR with github actions configured to pack and deploy nuget to the feed automatically

Yeah, that'll help a lot!

**Comment by Mezo-hx** [comment]
> Also, if you'd share what you'd like to include in potential future updates - would be great. Possibly someone from the community would be able to work on it

I'll probably be able to set up a Trello page for that, hopefully today since it's the weekend.

**Pull request merged**
